name: conda_env_BGCN_4_PLS_gpu
channels:
- conda-forge
- pyg
- pytorch
- defaults
dependencies:
- python=3.8
- cudatoolkit=11.3
- pytorch=1.10.0=py3.8_cuda11.3_cudnn8.2.0_0
- torchvision=0.11.0=py38_cu113
- torchaudio=0.10.0=py38_cu113
- openbabel=3.1.1
- scikit-learn-intelex=2021.5.0
- pandas=1.3.5
- biopandas=0.4.1
- pip=22.2.2
- pyg=2.0.4=py38_torch_1.10.0_cu113
- pytorch-lightning=1.5.9
- xorg-libxrender=0.9.10
- numpy=1.21.5
- scipy=1.7.3
- matplotlib=3.5.3
- oddt=0.7
- seaborn=0.12.1
- pip:
  - class-resolver==0.3.10