name: conda_env_HGScore_cpu
channels:
- conda-forge
- pyg
- pytorch
- defaults
dependencies:
- python=3.8
- pytorch=1.12.0=py3.8_cpu_0
- torchaudio=0.12.0=py38_cpu
- torchvision=0.13.0=py38_cpu
- openbabel=3.1.1
- scikit-learn-intelex=2021.5.0
- pandas=1.3.5
- biopandas=0.4.1
- pip=22.2.2
- pyg=2.2.0=py38_torch_1.12.0_cpu
- pytorch-lightning=1.7.7
- xorg-libxrender=0.9.10
- numpy=1.21.5
- scipy=1.7.3
- matplotlib=3.5.3
- oddt=0.7
- seaborn=0.12.1
- pip:
  - class-resolver==0.3.10