# Network Architecture
## Atomic Part
hetero_aggr: mean
num_layers: 3 # Number of layers for hidden_channels_la and hidden_channels_pa
heads: 1
### Ligand
hidden_channels_la:
- 36
- 57
- 91
### Protein
hidden_channels_pa:
- 42
- 50
- 60
## Molecular Part
num_timesteps: 5
## Final MLP
mlp_channels:
- 151
- 75
- 37
- 1
# Other Parameters
dropout: 0.08
lr: 0.001
weight_decay: 0.0001
batch_size: 64