dropout: 0.13
heads: 2
hetero_aggr: mean
hidden_channels_la:
- 48
- 76
- 121
hidden_channels_pa:
- 48
- 57
- 68
lr: 0.001
mlp_channels:
- 189
- 94
- 1
num_layers: 3
molecular_embedding_size: 4
str_for_hparams: 'InterMol length: 4.0A'
weight_decay: 0.0001
