dropout: 0.03
heads: 6
hetero_aggr: mean
hidden_channels_la:
- 38
- 34
- 30
- 27
hidden_channels_pa:
- 26
- 26
- 26
- 26
lr: 0.001
mlp_channels:
- 53
- 26
- 13
- 1
num_layers: 4
num_timesteps: 7
plot_path: /workspace/ODDT_to_Featurize/experiments/BG_PLS_OPTUNA_2/version_116
str_for_hparams: 'InterMol length: 4.0A'
weight_decay: 0.0001
